In [50]:
import pandas as pd
import numpy as np

In [51]:
df1 = pd.read_csv("od_country.csv")
df2 = pd.read_csv("od_type.csv")
df3 = pd.read_csv("us_waiting_list.csv")

In [52]:
df1.head(10)

,Country,Continent,Population_M,Deceased_Donors,Living_Donors,Total_Donors,Donor_Rate_PMP,Deceased_Rate_PMP,Total_Transplants,Kidney_Transplants,Liver_Transplants,Heart_Transplants,Lung_Transplants,Waiting_List,Year
0,Spain,Europe,47.8,2562,404,2966,62.05,53.60,5861,3508,1427,369,442,4800,2024
1,France,Europe,68.2,1925,611,2536,37.18,28.23,5634,3643,1355,477,372,10500,2024
2,Italy,Europe,58.9,1830,310,2140,36.33,31.07,4089,2331,1208,376,174,8200,2023
3,United Kingdom,Europe,67.7,1602,1005,2607,38.51,23.66,4734,3121,927,197,196,7000,2024
4,Germany,Europe,84.5,965,610,1575,18.64,11.42,3408,2069,780,339,310,8500,2023
5,Portugal,Europe,10.3,520,62,582,56.50,50.49,946,571,281,56,38,1800,2023
6,Belgium,Europe,11.7,425,90,515,44.02,36.32,1045,547,304,96,98,1300,2023
7,Croatia,Europe,3.9,195,18,213,54.62,50.00,370,220,100,30,20,500,2023
8,Netherlands,Europe,17.8,260,510,770,43.26,14.61,1310,860,250,52,86,1200,2023
9,Austria,Europe,9.1,210,60,270,29.67,23.08,620,380,150,55,35,900,2023

In [53]:
df2.head(2)

,Organ,Total_Transplants_Global,Living_Donor_Pct,Deceased_Donor_Pct,Avg_Wait_Years_US,Survival_Rate_1Y_Pct,Survival_Rate_5Y_Pct,Waiting_List_US,Can_Living_Donate,Common_Conditions,Description
0,Kidney,110467,37.0,63.0,3.6,97.0,90.0,91395,Yes,"Chronic Kidney Disease, Diabetes, Hypertension...",Most commonly transplanted organ. One kidney c...
1,Liver,42497,23.0,77.0,0.8,92.0,78.0,9053,Yes (partial),"Cirrhosis, Hepatitis B/C, Liver Cancer, Fatty ...",Second most transplanted organ. Living donors ...

In [54]:
df3.head(3)

,Year,Kidney,Liver,Heart,Lung,Pancreas,Intestine,Total,Transplants_Performed,Total_Donors
0,2015,83978,14719,4155,1454,1058,271,119362,30975,15070
1,2016,84529,14284,4283,1432,987,258,119518,33612,15948
2,2017,85220,13938,3892,1367,918,245,119022,34769,16474

**Missing Values Treatment**

In [55]:
df1.isnull().mean()

Country               0.0
Continent             0.0
Population_M          0.0
Deceased_Donors       0.0
Living_Donors         0.0
Total_Donors          0.0
Donor_Rate_PMP        0.0
Deceased_Rate_PMP     0.0
Total_Transplants     0.0
Kidney_Transplants    0.0
Liver_Transplants     0.0
Heart_Transplants     0.0
Lung_Transplants      0.0
Waiting_List          0.0
Year                  0.0
dtype: float64

In [56]:
def missing_report(df,name):
    report = pd.DataFrame({
        "Missing_Count" : df.isnull().sum(),
        "Missing_PCT" : ((df.isnull().sum() / len(df)) * 100).round(2),
        "Data_Types" : df.dtypes
    })
    return report[report['Missing_Count'] > 0].sort_values('Missing_PCT', ascending=False)

print(missing_report(df1,'od_country'))
print(missing_report(df2,    'od_type'))
print(missing_report(df3, 'us_waiting_list'))

Empty DataFrame
Columns: [Missing_Count, Missing_PCT, Data_Types]
Index: []
Empty DataFrame
Columns: [Missing_Count, Missing_PCT, Data_Types]
Index: []
Empty DataFrame
Columns: [Missing_Count, Missing_PCT, Data_Types]
Index: []

**Expected Missingness in Each Dataset & Treatment Rules**

In [57]:
df1.shape

(44, 15)

**Dataset 01**

In [58]:
df1.columns

Index(['Country', 'Continent', 'Population_M', 'Deceased_Donors',
       'Living_Donors', 'Total_Donors', 'Donor_Rate_PMP', 'Deceased_Rate_PMP',
       'Total_Transplants', 'Kidney_Transplants', 'Liver_Transplants',
       'Heart_Transplants', 'Lung_Transplants', 'Waiting_List', 'Year'],
      dtype='object')

In [59]:
df1["Lung_Transplants"].isnull().sum()

0

In [60]:
df1["Heart_Transplants"].isnull().sum()

0

In [61]:
df1["Waiting_List"].isnull().sum()

0

In [62]:
df1["Donor_Rate_PMP"].isnull().sum()

0

In [63]:
df1["Year"].isnull().sum()

0

**Dataset 01**

In [64]:
df2

,Organ,Total_Transplants_Global,Living_Donor_Pct,Deceased_Donor_Pct,Avg_Wait_Years_US,Survival_Rate_1Y_Pct,Survival_Rate_5Y_Pct,Waiting_List_US,Can_Living_Donate,Common_Conditions,Description
0,Kidney,110467,37.0,63.0,3.6,97.0,90.0,91395,Yes,"Chronic Kidney Disease, Diabetes, Hypertension...",Most commonly transplanted organ. One kidney c...
1,Liver,42497,23.0,77.0,0.8,92.0,78.0,9053,Yes (partial),"Cirrhosis, Hepatitis B/C, Liver Cancer, Fatty ...",Second most transplanted organ. Living donors ...
2,Heart,10287,0.0,100.0,0.5,88.0,77.0,3751,No,"Heart Failure, Cardiomyopathy, Coronary Artery...",Only from deceased donors. Requires precise ma...
3,Lung,8236,2.0,98.0,0.3,85.0,59.0,1068,Rare (lobar),"COPD, Pulmonary Fibrosis, Cystic Fibrosis, Pul...",One of the most challenging transplants. Singl...
4,Pancreas,2066,0.5,99.5,1.5,88.0,73.0,868,Rare (partial),"Type 1 Diabetes, Chronic Pancreatitis",Often combined with kidney transplant for diab...
5,Intestine,174,1.0,99.0,0.7,75.0,50.0,220,Rare,"Short Bowel Syndrome, Intestinal Failure, Croh...",Rarest organ transplant. Complex surgery with ...
6,Cornea,185000,0.0,100.0,0.1,95.0,90.0,0,No,"Keratoconus, Corneal Scarring, Fuchs' Dystrophy",Most commonly transplanted tissue. Very high s...
7,Bone Marrow / Stem Cells,95000,100.0,0.0,0.4,62.0,50.0,0,Yes,"Leukemia, Lymphoma, Sickle Cell Disease, Aplas...",Living donation through peripheral blood or bo...

In [65]:
df2.columns

Index(['Organ', 'Total_Transplants_Global', 'Living_Donor_Pct',
       'Deceased_Donor_Pct', 'Avg_Wait_Years_US', 'Survival_Rate_1Y_Pct',
       'Survival_Rate_5Y_Pct', 'Waiting_List_US', 'Can_Living_Donate',
       'Common_Conditions', 'Description'],
      dtype='object')

In [66]:
df2["Common_Conditions"].isnull().sum()

0

In [67]:
df2["Description"].isnull().sum()

0

In [68]:
df2["Can_Living_Donate"].isnull().sum()

0

In [69]:
df2["Waiting_List_US"].isnull().sum()

0

**Dataset 03**

In [70]:
df3.head(4)

,Year,Kidney,Liver,Heart,Lung,Pancreas,Intestine,Total,Transplants_Performed,Total_Donors
0,2015,83978,14719,4155,1454,1058,271,119362,30975,15070
1,2016,84529,14284,4283,1432,987,258,119518,33612,15948
2,2017,85220,13938,3892,1367,918,245,119022,34769,16474
3,2018,83672,13163,3798,1320,903,234,116470,36530,17579

In [71]:
df3.columns

Index(['Year', 'Kidney', 'Liver', 'Heart', 'Lung', 'Pancreas', 'Intestine',
       'Total', 'Transplants_Performed', 'Total_Donors'],
      dtype='object')

In [72]:
df3.count()

Year                     10
Kidney                   10
Liver                    10
Heart                    10
Lung                     10
Pancreas                 10
Intestine                10
Total                    10
Transplants_Performed    10
Total_Donors             10
dtype: int64

In [73]:
# check mising values in each columns
for col in df3.columns:
    missing_val = df3[col].isnull().sum()
    print(f"Column {col} has {missing_val} missing values")

Column Year has 0 missing values
Column Kidney has 0 missing values
Column Liver has 0 missing values
Column Heart has 0 missing values
Column Lung has 0 missing values
Column Pancreas has 0 missing values
Column Intestine has 0 missing values
Column Total has 0 missing values
Column Transplants_Performed has 0 missing values
Column Total_Donors has 0 missing values

In [79]:
organ_cols = ['Kidney', 'Liver', 'Heart', 'Lung', 'Pancreas', 'Intestine']
organ_cols

['Kidney', 'Liver', 'Heart', 'Lung', 'Pancreas', 'Intestine']